# Generated by Django 4.2.3 on 2023-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsystem',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
